spring:
  jpa:
    database: mysql
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://root.chzhhyf6xvc5.us-east-2.rds.amazonaws.com:3306/sys
    username: admin
    password: 20110518

kakao:
  auth-token-uri: https://kauth.kakao.com/oauth/token
  rest-api-key: 9a14ba30e24aec9b0b85c4c47c83bcab
  redirect-uri: http://ec2-3-136-31-1.us-east-2.compute.amazonaws.com:8080/api/kakologin
  user-me-uri: https://kapi.kakao.com/v2/user/me
  access-token-info-uri: https://kapi.kakao.com/v1/user/access_token_info